import assert from 'node:assert/strict';
import { test } from 'node:test';

import { DEFAULT_FIXTURES_DIR } from '../../src/config.js';
import { validateTranscript } from '../../src/analysis/contract.js';
import { createTranscriptService } from '../../src/transcript/index.js';
import {
  createFixtureTranscriptProvider,
  loadTranscriptFixtures,
  toProviderCues
} from '../../src/api/fixture-transcripts.js';

const VIDEO_ID = 'demoTalk001';

test('the canonical manifest supplies at least the demo transcript', () => {
  const fixtures = loadTranscriptFixtures(DEFAULT_FIXTURES_DIR);

  assert.ok(fixtures.has(VIDEO_ID));
  assert.deepEqual(validateTranscript(fixtures.get(VIDEO_ID)), { valid: true, errors: [] });
});

test('a missing fixtures directory yields no fixtures rather than throwing', () => {
  assert.equal(loadTranscriptFixtures('/definitely/not/here').size, 0);
});

test('segments become provider cues in milliseconds', () => {
  const transcript = loadTranscriptFixtures(DEFAULT_FIXTURES_DIR).get(VIDEO_ID);
  const cues = toProviderCues(transcript);

  assert.equal(cues.length, transcript.segments.length);
  assert.equal(cues[0].startMs, Math.round(transcript.segments[0].startTime * 1000));
  assert.equal(cues[0].durationMs, Math.round((transcript.segments[0].endTime - transcript.segments[0].startTime) * 1000));
  assert.equal(cues[0].speaker, transcript.segments[0].speaker);
});

test('the mock path runs the real transcript service and normalizer', async () => {
  const transcripts = createTranscriptService({ provider: createFixtureTranscriptProvider() });

  const transcript = await transcripts.getTranscript({ videoId: VIDEO_ID, language: 'en-US' });

  assert.deepEqual(validateTranscript(transcript), { valid: true, errors: [] });
  assert.equal(transcript.videoId, VIDEO_ID);
  assert.equal(transcript.segments[0].speaker, 'Maya Chen');
  // Ids are regenerated by the normalizer, so they are content-derived rather
  // than the fixture's editorial seg_001 labels.
  assert.match(transcript.segments[0].id, /^[A-Za-z][A-Za-z0-9_-]*$/);
});

test('an unknown video reports what mock mode can serve', async () => {
  const provider = createFixtureTranscriptProvider();

  await assert.rejects(() => provider.fetchTranscript({ videoId: 'missingVid1', language: 'en-US' }), (error) => {
    assert.equal(error.code, 'VIDEO_NOT_FOUND');
    assert.match(error.message, /ANALYSIS_MODE=live/);
    assert.ok(error.details.availableVideoIds.includes(VIDEO_ID));
    return true;
  });
});

test('a language the fixture cannot satisfy fails the way the real provider would', async () => {
  const provider = createFixtureTranscriptProvider();

  await assert.rejects(() => provider.fetchTranscript({ videoId: VIDEO_ID, language: 'de' }), (error) => {
    assert.equal(error.code, 'UNSUPPORTED_LANGUAGE');
    return true;
  });

  // A base-language request still matches the regional fixture.
  const matched = await provider.fetchTranscript({ videoId: VIDEO_ID, language: 'en' });
  assert.equal(matched.language, 'en-US');
});

test('an unavailable caption source is refused rather than substituted', async () => {
  const provider = createFixtureTranscriptProvider();

  await assert.rejects(
    () => provider.fetchTranscript({ videoId: VIDEO_ID, language: 'en-US', captionSource: 'automatic' }),
    (error) => {
      assert.equal(error.code, 'UNSUPPORTED_LANGUAGE');
      assert.deepEqual(error.details.available, ['manual']);
      return true;
    }
  );
});

test('available ids are reported for the startup banner', () => {
  assert.ok(createFixtureTranscriptProvider().availableVideoIds().includes(VIDEO_ID));
});
